language: python
sudo: required
services:
- docker
python:
- 3.5
- 3.6
env:
  matrix:
  - PYTHONASYNCIODEBUG=1
install:
- pip install flake8
- pip install pytest pytest-cov pytest-catchlog docker-py pytest-mock
- pip install codecov
- pip install .
script:
- make cov
after_success:
- codecov
deploy:
  provider: pypi
  user: fabregas
  password:
    secure: GbRQ988hvprSmeURr7aYFY3zQt4C0jhz6E0SLtWyjjnVx2i63ROwSDNpPqrmTlbwEipwJfWff7gasN6g12cjNAlKQxfRn8/Pz533I2rkG9dgUPARV9H9v9pMm3aGEmI3POcemXZQE2bxjPvtjbVnoSlaquY+lbVW0aJR9g69P+OwLEKn3PvsR4RgipbtoXkC1iKdydeWmq07Yc9oPVqEsqp7/cHo2xSSJ+6k6BdTIhtGemCACusRLW6AyuVYa4PBKhpY4VUP3aBM1vTNKzu9ViG/Sa+HJtvkAFtbEtoYHT6nhR/biaxJQ9qRx9QXpTRPyvslMT7oW7mOCR4NEFhgHx2+r4znvPL9vCkBueFq05tTwlQr3niKcfZGuoPTMJ0eAjwq1cPVPFjrd12Cy6PPDWytwfnEuGschMV8S87QmVkj7krhiB1DFnB/PxQVJ2z7Nrfd4mKnbEdBHJBkqbrFzQEABG4BLnBB+EhyarvLSH3x+RYVUNPvOdUk41hz5yB+QRZNV7GbZSs7b4Qoh4FMPYrpE7brTw7dEFZQfcDHz8FkLenFw/gQqMTTgfFXnUuIEgDPMghJyBuG9rxuB+rp9xYDGs6wg4WyaPWh//Qdiho+dJ4pRms2HA5bcf3kx9tZbsOc4q1I8lpzu5EH413Fx1rZwvCbvQViqSRqnUv2di8=
  distributions: sdist
  on:
    tags: true
    python: 3.5
